apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: developer-hub-postgres
  description: The Postgres database used by Developer Hub for storing catalog and plugin data.
spec:
  type: database
  owner: group:rhdh
  tags:
    - backstage
    - rhdh
    - postgres
    - database
  partOf:
    - resource:default/dev-cluster-infra
  ownedBy:
    - group:default/rhdh
  usedBy:
    - component:default/developer-hub

