apiVersion: backstage.io/v1beta1
kind: Resource
metadata:
  namespace: default
  name: quay-registry
  description: The Quay container image registry used by the OpenShift cluster.
spec:
  type: image-registry
  owner: group:rhdh
  partOf:
    - resource:default/dev-cluster-infra
links:
  - url: https://quay-GUID.apps.cluster-GUID.GUID.CLUSTER.opentlc.com/
    title: Quay Console