apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: developer-hub
  description: An internal developer portal providing a Software Catalog and integrations.
spec:
  type: service
  tags:
    - nodejs
  lifecycle: production
  owner: group:rhdh
  partOf:
    - system:default/developer-hub
