apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: gitlab
  description: Git repository and CI platform.
spec:
  type: dev-service
  lifecycle: production
  owner: group:rhdh
  partOf:
    - system:default/dev-cluster-services
  dependsOn:
    - resource:default/developer-hub-postgres
    - resource:default/openshift-api-server
    - resource:default/quay-registry
    - component:default/developer-hub-gitops