apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: janus-gitops
  description: OpenShift GitOps (Argo CD) cluster used to manage infrastructure.
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: dev-cluster-services
  partOf:
    - system:default/dev-cluster-services
