apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: openshift-pipelines
  description: A Kubernetes-native CI/CD system based on Tekton Pipelines.
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: dev-cluster-services
  partOf:
    - system:default/dev-cluster-services
  consumesApi:
    - api:default/quay-api