apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openshift-gitops
  description: OpenShift GitOps (Argo CD) cluster used to manage infrastructure.
  links:
  - url: https://argocd-server-openshift-gitops{{ cluster_subdomain }}
    title: Infrastructure GitOps
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: dev-cluster-services
  partOf:
    - system:default/dev-cluster-services
  consumesApis:
    - api:default/openshift-cluster-api