apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: quay
  description: A container image registry service.
  links:
    - url: https://quay-GUID.apps.cluster-GUID.GUID.CLUSTER.opentlc.com/
      title: Quay Console
spec:
  type: image-registry
  lifecycle: production
  owner: group:rhdh
  system: dev-cluster-services
  partOf:
    - system:default/dev-cluster-services
  providesApi:
    - api:default/quay-api