apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: quay
  description: A container image registry service.
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: dev-cluster-services
relations:
  - type: partOf
    targetRef: system:default/dev-cluster-services
